### ISSUE TITLE
ESCPOS vs ESCPOS_NET?

### ISSUE THREAD

**Issue by lukevp** [igorocampos/ESCPOS#8]
Igoro,
I'm curious why you started a new .net printer library?  Were there some architecture/design decisions in ESCPOS_NET that you didn't agree with?

It already has some momentum so it would be nice if we could work together, but if there are some fundamental differences or some reason it doesn't meet your needs, that's fine too.

Best,
-Luke

**Comment by igorocampos** [comment]
Hi Luke, I actually did my library before I came to know yours.

Mine is a very simplified one that covers the needs that I had at the time. The library I was using before was not open source and was not compatible with .NET Core, so when I started to migrate some projects to .NET Core, I didn't think twice and developed my own according to my needs. I guess I should have searched better before ¯\_(ツ)_/¯ Sorry about that. 

Then, during DO's Hacktoberfest I came across yours because I looked for topics I was already into. 

If you need some specific help with your library, I would be glad to help in my spare time :)

Cheers,
Igor

**Comment by igorocampos** [comment]
@lukevp if you feel like it, please reopen this issue :)
